
# ------------------------------------------
# 
# THIS MAKE FILE GENERATED BY make_make.py
# 
# ------------------------------------------
debug: all
all:
	make -f debug_make
                
release:
	make -f release_make

clean:
	rm src/build/* src/lib_code/build/*